detected_signatures = [
    'netunit',
    'soclose.ru',
    'ida64',
    'ida32',
    'ida ',
    ' ida',
    'hack',
    'cheat',
    'netunit',
    'aimbot',
    'wallhack',
    'icode ',
    ' icode',
    'icoded',
    'multihit',
    'multikill',
    'antiban',
    'inject',
    'winhook',
    'procexp',
    'procmon',
    'x64dbg',
    'triggerbot',
    'reversing',
    'yougame',
    'xmod',
    'autofire',
    'minhook',
    'wallshot',
    'wallshoot',
    'aceid',
    'kiero',
    'autokill',
    'IGameFunction',
    'SRWIHook',
    'VMTable',
    'чит',
    'взлом',
    'аимбот',
    'debugview',
    'dbgview',
    'winobj'
    'spoofer',
    'ExternalLauncher.exe',
    'schokk',
    'qweex',
    'hwid',
    'nixware',
    'trainer',
    'clicker',
    'Game_dump'
]

detected_runtime_signatures = [
    'visualstudio',
    'visual studio',
    'regedit',
    # 'vscode',
    'mobaxtern',
    'vmware',
    'virtualbox',
    'vbox'
]

exception_files = [
    'mavinject.exe',
    'ttdinject.exe',
    'InputInjectionBroker.dll'
]